const filaDoBanco = []
// pessoas acima de 65 anos tem prioridade
// pessoas abaixo de 18 anos NÃO tem prioridade
console.log(filaDoBanco)

// filaDoBanco.forEach((item) => console.log(item))
// filaDoBanco.reverse()
// console.log(filaDoBanco)
// filaDoBanco.sort()
// console.log(filaDoBanco)
//  //retorna o indice do item encontrado
//  console.log(filaDoBanco.includes('Zenilda')) // retorna true ou false

// if(filaDoBanco.includes('local')){
//     console.log ('estamos em um ambiente de desenvolvimento')
// }


// propriedades são funçoes predefinidas para atalhos ou para funcionalidades 
//console.log(filaDoBanco)
//filaDoBanco.push('Antonio') // adiciona ao fim
//console.log(filaDoBanco)
//filaDoBanco.unshift('Beatriz') // adiciona no começo
//console.log(filaDoBanco)
//filaDoBanco.pop() //remove do final
//console.log(filaDoBanco)
//filaDoBanco.shift() //remove do começo
//console.log(filaDoBanco)